# 第十五章 友元、异常和其他



本章内容包括：

- 友元类；
- 友元类方法；
- 嵌套类；
- 引发异常、`try`块和`catch`块；
- 异常类；
- 运行阶段类型识别（RTTI）；
- `dynamic_cast` 和 `typeid`；
- `static_cast`、`const_cast` 和 `reiterpret_cast`。

## 1、15.1  友元

让<font color="RoyalBlue">Remote::set_chan( )</font>成为Tv类的友元的方法是，在Tv类声明中将其声明为友元：

```C++
Class TV
{
	friend void Remote::set_chan( TV & t, int);
}
```

### 15.1.2 前向声明(forward declaration)

```C++
class TV;
class Remote{...}
class TV;
```

![image-20210815204948714](https://static.fungenomics.com/images/2021/08/image-20210815204948714.png)



## 15.2、嵌套类

## 15.3、 异常

#### 15.3.3 异常机制

>   引发异常
>
>   使用处理程序捕获异常
>
>   使用try块

程序使用异常处理程序（exception handler）

<font color="red">catch</font>关键字表示<font color="RoyalBlue">捕获异常</font>。<font color="RoyalBlue">处理程序</font>以关键字<font color="RoyalBlue">catch</font>开头，随后是位于括号中的类型声明，它指出了异常处理程序要响应的异常类型；

然后是一个用花括号括起的代码块，指出要采取的措施。<font color="green">catch关键字和异常类型</font>用作标签，指出当异常被引发时，程序应跳到这个位置执行。

<font color="RoyalBlue">异常处理程序也被称为catch块</font>。

<font color="red">try块标识</font>其中特定的异常可能被激活的代码块，它后面跟一个或多个catch块。<font color="green">try块是由关键字try指示的</font>，关键字try的后面是一个由花括号括起的代码块，表明需要注意这些代码引发的异常。

要了解这3个元素是如何协同工作的，最简单的方法是看一个简短的例子，如程序清单15.9所示。

```C++
// error3.cpp -- using an exception
#include <iostream>
double hmean(double a, double b);

int main()
{
    double x, y, z;
    std::cout << "Enter two numbers: ";
    while (std::cin >> x >> y)
    {
        try {                   // start of try block
            z = hmean(x,y);
        }                       // end of try block
        catch (const char * s)  // start of exception handler
        {
            std::cout << s << std::endl;
            std::cout << "Enter a new pair of numbers: ";
            continue;
        }                       // end of handler
        std::cout << "Harmonic mean of " << x << " and " << y
            << " is " << z << std::endl;
        std::cout << "Enter next set of numbers <q to quit>: ";
    }
    std::cout << "Bye!\n";
    return 0;
}

double hmean(double a, double b)
{
    if (a == -b)
        throw "bad hmean() arguments: a = -b not allowed";
    return 2.0 * a * b / (a + b); 
}
```

<font color="red">try</font>	特定异常激活代码块 <font color="green">-></font><font color="red">    throw</font>	引发异常 <font color="green">-></font> <font color="red">catch</font>	捕获异常 <font color="green">-></font>	<font color="RoyalBlue">执行catch 块</font> 处理异常

<font color="red">char*s</font>则表明该处理程序与字符串异常匹配。

s与函数参数定义极其类似，因为匹配的引发将被赋给s。另外，当异常与该处理程序匹配时，程序将执行括号中的代码。

<img src="E:/dev/Typora-Note/C++/CPP%20Primer%20Plus%20-%206/chapter15.assets/image-20230729003328388.png" alt="image-20230729003328388" style="zoom:50%;" />

#### 15.3.7 其他异常特性和

由于不知道异常的类型可以使用省略号来表示异常，以此捕获任何异常

```c++
catch (...){//statements}	//catches any type exception
```

#### 15.3.8 exception类

##### 1 stdexcept类

头文件stdexcept定义了其他几个异常类。首先，该文件定义了 logic_error和runtime_error类，它们都是以公有方式从exception派生而来的：

```c++
domain_error;
invalid_argument;
length_errir;
out_of_bounds;
```

每个类独有一个类似于logic_error的构造函数，让您能够提供一个供方法what( )返回的字符串。

```c++
try{
    ...
}
catch(out_of_bounds & oe){...}
catch(logic_error & oe){...}
catch(exception & oe){...}
```

##### 2 bad_alloc异常和new

对于使用<font color="red">new导致的内存分配问题</font>

C++的最新处理方式是让new引发<font color="green">bad_alloc</font>异常。头文件new包含bad_alloc类的声明，它是从exception 类公有派生而来的。但在以前，当无法分配请求的内存量时，new返回 一个空指针，然后我们可以 <font color="RoyalBlue">exit(EXIT_FAILURE)</font>。

```c++
// newexcp.cpp -- the bad_alloc exception
#include <iostream>
#include <new>
#include <cstdlib>  // for exit(), EXIT_FAILURE
using namespace std;

struct Big
{
    double stuff[20000];
};

int main()
{
    Big * pb;
    try {
        cout << "Trying to get a big block of memory:\n";
        pb = new Big[10000]; // 1,600,000,000 bytes
        cout << "Got past the new request:\n";
    }
    catch (bad_alloc & ba)
    {
        cout << "Caught the exception!\n";
        cout << ba.what() << endl;
        exit(EXIT_FAILURE);
    }
    cout << "Memory successfully allocated\n";
    pb[0].stuff[0] = 4;
    cout << pb[0].stuff[0] << endl;
    delete [] pb;
    // cin.get();
    return 0; 
}
```

>   ```c++
>   Trying to get a big block of memory:
>   Caught the exception!
>       std::bad_alloc
>   ```

在这里，方法what( )返回字符串“<font color="DarkOrchid ">std::bad_alloc</font>”。

### 15.3.10 异常何时会迷失方向

未捕获异常不会导致程序立刻异常终止。相反，程序将首先调用函数terminate( )。在默认情况下，terminate( )调用abort( )函数。

可以指定 terminate( )应调用的函数（而不是abort( )）来修改terminate( )的这种行为。为此，可调用<font color="RoyalBlue">set_terminate( )函数。set_terminate( )和terminate( )</font>都是在头文件exception中声明的：

```c++
set_terminate(funtion);
```

发生异常没有被捕获，系统调用<font color="DarkOrchid ">terminate（）</font>随后调用 funtion

发生意外异常，程序调用<font color="DarkOrchid ">unexpected()</font>，这个函数将会调用<font color="red">terminate</font>，后者默认调用<font color="DarkOrchid ">abort（）</font>

正如有一个可用于修改<font color="DarkOrchid ">terminate( )</font>的行为的<font color="green">set_terminate( )</font>函数一样，也有一个可用于修改<font color="DarkOrchid ">unexpected( )</font>的行为的<font color="green">set_unexpected( )</font>函数。这些新函数也是在头文件exception中声明的

与提供给set_terminate( )的函数的行为相比，提供给 set_unexpected( )的函数的行为受到更严格的限制。具体地说， unexpected_handler函数可以：

<font color="red"> 通过调用terminate( )（默认行为）</font>、abort( )或exit( )来终止程序；

引发异常。

引发异常（第二种选择）的结果取决于<font color="DarkOrchid ">unexpected_handler</font>函数所引发的异常以及引发意外异常的函数的异常规范：

1.  如果新引发的异常与原来的异常规范匹配，则程序将从那里开始进行正常处理，即寻找与新引发的异常匹配的catch块。基本上，这种方法将用<font color=#FFCE70>预期的异常取代意外异常</font>；
2.  如果新引发的异常与原来的异常规范不匹配，且异常规范中没有包括<font color="RoyalBlue">std ::bad_exception</font>类型，则程序将调用<font color="DarkOrchid ">terminate( )</font>。 bad_exception是从exception派生而来的，其声明位于头文件exception中；
3.  如果新引发的异常与原来的异常规范不匹配，且原来的异常规范中包含了<font color="RoyalBlue">std ::bad_exception</font>类型，则不匹配的异常将被std::bad_exception异常所取代。

如果要捕获所有的异常（不管是预期的异常还是意外异常），则可以这样做：

```c++
#include <exception>
using namespeace std;
```

设计一个替代函数，将意外异常转换为<font color="red">bad_exception</font>异常，该函数的原型如下：

```c++
void myUnexpected(){
    throw std::bad_exception;		//or just throw
}
```

仅使用throw，而不指定异常将导致重新引发原来的异常。然而，如果异常规范中包含了这种类型，则该异常将被<font color="red">bad_exception</font>对象所取代。

接下来在程序的开始位置，将意外异常操作指定为调用该函数：

```c++
set_unexpected(MyUnexpected);
```

## 15.4 RTTI

RTTI(Runtime type identification)

#### 15.4.2 工作原理

1.  如果可能的话，<font color="red">dynamic_cast</font>运算符将使用一个指向基类的指针来生成一个指向派生类的指针；否则，该运算符返回0——空指针。
2.  <font color="red">typeid</font>运算符返回一个指出<font color="green">对象的类型</font>的值。
3.  <font color="red">type_info</font>结构存储了有关特定类型的信息。

只能将RTTI用于包含虚函数的类层次结构，原因在于只有对于这种类层次结构，才应该将<font color=#FFCE70>派生对象的地址赋给基类指针</font>。

>   <font color="DarkOrchid ">提示：</font>RTTI只适用于包含<font color="RoyalBlue">虚函数</font>的类。



##### 1、dynamic_cast运算符

dynamic_cast运算符是最常用的RTTI组件，它不能回答“<font color="green">指针指向的是哪类对象</font>”这样的问题，但能够回答“<font color="aqua">是否可以安全地将对象的地址赋给特定类型的指针</font>”这样的问题。

我们来看一看这意味着什么。假设有下面这样的类层次结构：

```c++
class Gramd{	//has virtual methods};
class Superb:public Gramd{...};
class Magnificent:public Superb{...};
```

接下来假设有下面的指针：

```c++
Gramd * pg = new Grand;
Gramd * ps = new Superb;
Gramd * pm = new Magnificent;
```

最后，对于下面的类型转换：

```c++
Magnificent * p1 = (Magnificent *)	pm;	//#1
Magnificent * p2 = (Magnificent *)	pg;	//#2
Superb * p3 = (Magnificent *) pm;		//#3
```

先来看一下<font color="red">dynamic_cast</font>的语法。该运算符的用法如下，其中pg指向一个对象：

```c++
Superb * pm = dynamic_cast<Superb *>;
```

这提出了这样的问题：指针pg的类型是否可被安全地转换为<font color="DarkOrchid ">Superb *</font>？如果可以<font color="red">运算符将返回对象的地址</font>，否则返回一个<font color="RoyalBlue">空指针</font>。


## 15.6 总结

友元使得能够为类开发更灵活的接口。类可以将其他函数、其他类 和其他类的成员函数作为友元。在某些情况下，可能需要使用前向声 明，需要特别注意类和方法声明的顺序，以正确地组合友元。

嵌套类是在其他类中声明的类，它有助于设计这样的助手类，即实 现其他类，但不必是公有接口的组成部分。
